server:
  port: ${PORT:8080}
  http2:
    enabled: true
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
      - SaveSession
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders : "*"
  data:
    mongodb:
      uri: mongodb+srv://firstuser:mongodbnosql@db-test.ol7gz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: db-test
    redis:
      repositories:
        enabled: true
  session:
    store-type: redis
    redis:
      save-mode: on-set-attribute
  redis:
    database: 1
  security:
    oauth2:
      client:
        registration:
          google:
            authorization-grant-type: authorization_code
            client-id: 491877475842-meqk5iqgu1snm9r0925q312fkktpovt6.apps.googleusercontent.com
            client-secret: I2IRJKA2HnFzfxig8uVguP4h
            redirect-uri: https://www.icaland.id/login/oauth2/code/google
            scope:
            - email
            - profile
            - openid
        provider:
          google:
            issuer-uri: https://accounts.google.com
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  

        